---
- name: Server Setup
  hosts: mansible
  become: true
  tasks:
    - name: Update yum cache (CentOS/RHEL)
      yum:
        update_cache: yes

    - name: Add user with sudo privileges
      user:
        name: nedko
        password: "{{ 'someExtraStrongPassword' | password_hash('sha512', 'mysecretsalt') }}"
        createhome: yes
        shell: /bin/bash
        groups: wheel
        append: yes
      become: true
      become_method: sudo

    - name: Install EPEL repository (CentOS/RHEL)
      yum:
        name: epel-release
        state: present

    - name: Install Nginx (CentOS/RHEL)
      yum:
        name: nginx
        state: present

    - name: Start Nginx (CentOS/RHEL)
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install MySQL (CentOS/RHEL)
      yum:
        name: mysql-server
        state: present

    - name: Start MySQL Service (CentOS/RHEL)
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install PHP and required extensions (CentOS/RHEL)
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - php-fpm
        - php-mysqlnd
        - php-mbstring
        - php-xml
        - php-curl
        - php-gd

    - name: Restart PHP-FPM (CentOS/RHEL)
      service:
        name: php-fpm
        state: restarted

    # - name: Disable root SSH login
    #   lineinfile:
    #     dest: /etc/ssh/sshd_config
    #     regexp: "^PermitRootLogin"
    #     line: "PermitRootLogin no"
    #   notify: Restart SSH Service

    - name: Install and configure firewalld (CentOS/RHEL)
      yum:
        name: firewalld
        state: present

    - name: Enable firewalld service
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Add firewall rules
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - ssh
        - http
        - https